import { useAppPreferences } from "../context/AppPreferences";

const copy = {
  es: {
    dashboard: "Panel",
    trends: "Tendencias",
    analytics: "Analisis",
    settings: "Configuracion",
    welcome: "Bienvenido de vuelta",
    search: "Buscar tendencias",
    recommended: "Recomendadas",
    notifications: "Notificaciones",
    active: "activas",
    user: "Usuario",
    premium: "Plan Premium",
    totalMentions: "Menciones Totales",
    trendLeader: "Tendencia Lider",
    averageGrowth: "Crecimiento Promedio",
    estimatedInteractions: "Interacciones Estimadas",
    featuredTrend: "Tendencia Destacada",
    weeklyActivity: "Actividad Semanal",
    impressions: "Impresiones",
    engagement: "Engagement",
    clicks: "Clicks",
    activeTrends: "Tendencias Activas",
    trackedHashtags: "Hashtags Monitoreados",
    resultsFor: "Resultados para",
    noTrendResults: "No encontramos tendencias con esa busqueda.",
    sourceDistribution: "Distribucion por Fuente",
    platforms: "Plataformas",
    strongestTrends: "Tendencias Mas Fuertes",
    detailedAnalysis: "Analisis Detallado",
    realSummary: "Resumen real de fuentes, estados y rendimiento de tendencias",
    estimatedEvolution: "Evolucion Estimada",
    currentSeries: "Serie derivada del comportamiento actual de las tendencias",
    byAge: "Por Edad",
    byGender: "Por Genero",
    estimatedAudience: "Audiencia estimada",
    trendStatus: "Estado de Tendencias",
    platformPerformance: "Rendimiento por Plataforma",
    exportReport: "Exportar Reporte",
    latestCapture: "Ultima captura",
    saveProfile: "Guardar Perfil",
    profile: "Perfil",
    appearance: "Apariencia",
    language: "Idioma",
    privacy: "Privacidad",
    account: "Cuenta",
    subscription: "Suscripcion",
    status: "Estado",
    activeState: "Activo",
    pausedState: "Pausado",
    deactivateAccount: "Pausar cuenta",
    restoreAccount: "Reactivar cuenta",
    resetAccount: "Restablecer ajustes",
    publicProfile: "Perfil publico",
    showStats: "Mostrar estadisticas",
    allowMessages: "Permitir mensajes",
    trendAlerts: "Alertas de tendencias",
    weeklyReports: "Reportes semanales",
    mentions: "Menciones",
    appUpdates: "Actualizaciones del sistema",
    editPhoto: "Cambiar foto",
    username: "Nombre de usuario",
    email: "Email",
    bio: "Biografia",
    dataSaved: "Cambios guardados",
    accountLocalNote:
      "Estos cambios se guardan en tu cuenta y se sincronizan con tu sesion.",
    noPreview:
      "Vista previa no disponible para esta fuente. Puedes abrir la noticia o tendencia en su fuente original.",
    openSource: "Abrir fuente",
    pageNotFound: "Pagina no encontrada",
    pageNotFoundText:
      "Lo sentimos, la pagina que buscas no existe o ha sido movida.",
    backToDashboard: "Volver al Panel",
    markAll: "Marcar todo",
    historicalMatches: "Coincidencias en historial",
    capturedOn: "Capturada el",
    logout: "Salir",
    sentiment: "Sentimiento",
    lifecycle: "Fase",
    riskLevel: "Riesgo",
    actions: "Acciones sugeridas",
    geoFocus: "Foco geografico",
    keywords: "Keywords sugeridas",
    recommendedFormatLabel: "Formato recomendado",
    crisisMonitor: "Monitor de crisis",
    crisisPriority: "Prioridad",
    noCrisisAlerts: "No hay alertas criticas fuertes en este momento.",
    mexicoHeatmap: "Mapa de Mexico",
    regionalPulse: "Pulso regional",
    sourceFilter: "Fuente",
    categoryFilter: "Categoria",
    allSources: "Todas",
    allCategories: "Todas",
    stateDetail: "Detalle del estado",
    topTrendsInState: "Tendencias fuertes en esta zona",
    dominantSources: "Fuentes dominantes",
    dominantCategories: "Categorias dominantes",
    heatLegend: "Leyenda del mapa",
    lowIntensity: "Baja",
    mediumIntensity: "Media",
    highIntensity: "Alta",
    openTrendDetail: "Abrir detalle",
    clickStateHint: "Haz clic en un estado para ver tendencias y contexto.",
    hoverStateHint: "Pasa el mouse sobre el mapa para ver el pulso regional.",
    noStateSelected: "Selecciona un estado en el mapa para ver su detalle.",
    generalCategory: "General",
    highSeverity: "Alta",
    mediumSeverity: "Media",
    lowSeverity: "Baja",
    noGeoData: "Sin datos regionales fuertes.",
    positive: "Positivo",
    negative: "Negativo",
    mixed: "Mixto",
    emerging: "Emergente",
    peak: "Pico",
    fading: "En descenso",
    temporalComparison: "Comparacion temporal",
    historicalEvolution: "Evolucion historica",
    realHistorySeries: "Serie construida con snapshots reales guardados en la base de datos",
    vsPreviousCapture: "vs captura anterior",
    risingNow: "Subiendo ahora",
    coolingDown: "Bajando ahora",
    newEntries: "Nuevas entradas",
    viewDetail: "Ver detalle",
    close: "Cerrar",
    temporalDetail: "Detalle temporal",
    dataOrigin: "Procedencia de datos",
    methodologyNote: "Metodologia",
    loadingData: "Cargando datos",
    loadingDataMessage: "Trend Flow esta consultando fuentes y preparando la vista.",
    loadFailed: "No pudimos cargar esta vista",
    loadFailedMessage: "Puedes reintentar o revisar si el backend esta disponible.",
    retry: "Reintentar",
    methodologyTitle: "Como interpretar esta vista",
    academicPositioning:
      "Trend Flow es una plataforma de monitoreo y apoyo a decision. Algunas capas son reales y otras son estimadas o heuristicas.",
  },
  en: {
    dashboard: "Dashboard",
    trends: "Trends",
    analytics: "Analytics",
    settings: "Settings",
    welcome: "Welcome back",
    search: "Search trends",
    recommended: "Recommended",
    notifications: "Notifications",
    active: "active",
    user: "User",
    premium: "Premium Plan",
    totalMentions: "Total Mentions",
    trendLeader: "Trend Leader",
    averageGrowth: "Average Growth",
    estimatedInteractions: "Estimated Interactions",
    featuredTrend: "Featured Trend",
    weeklyActivity: "Weekly Activity",
    impressions: "Impressions",
    engagement: "Engagement",
    clicks: "Clicks",
    activeTrends: "Active Trends",
    trackedHashtags: "Tracked Hashtags",
    resultsFor: "Results for",
    noTrendResults: "No trends matched that search.",
    sourceDistribution: "Source Distribution",
    platforms: "Platforms",
    strongestTrends: "Strongest Trends",
    detailedAnalysis: "Detailed Analytics",
    realSummary: "Real summary of sources, states, and trend performance",
    estimatedEvolution: "Estimated Evolution",
    currentSeries: "Series derived from current trend behavior",
    byAge: "By Age",
    byGender: "By Gender",
    estimatedAudience: "Estimated audience",
    trendStatus: "Trend Status",
    platformPerformance: "Platform Performance",
    exportReport: "Export Report",
    latestCapture: "Latest capture",
    saveProfile: "Save Profile",
    profile: "Profile",
    appearance: "Appearance",
    language: "Language",
    privacy: "Privacy",
    account: "Account",
    subscription: "Subscription",
    status: "Status",
    activeState: "Active",
    pausedState: "Paused",
    deactivateAccount: "Pause account",
    restoreAccount: "Restore account",
    resetAccount: "Reset settings",
    publicProfile: "Public profile",
    showStats: "Show stats",
    allowMessages: "Allow messages",
    trendAlerts: "Trend alerts",
    weeklyReports: "Weekly reports",
    mentions: "Mentions",
    appUpdates: "System updates",
    editPhoto: "Change photo",
    username: "Username",
    email: "Email",
    bio: "Bio",
    dataSaved: "Changes saved",
    accountLocalNote:
      "These changes are saved to your account and synced with your session.",
    noPreview:
      "Preview is not available for this source. You can open the original article or trend source.",
    openSource: "Open source",
    pageNotFound: "Page not found",
    pageNotFoundText:
      "Sorry, the page you are looking for does not exist or has moved.",
    backToDashboard: "Back to Dashboard",
    markAll: "Mark all",
    historicalMatches: "Historical matches",
    capturedOn: "Captured on",
    logout: "Logout",
    sentiment: "Sentiment",
    lifecycle: "Lifecycle",
    riskLevel: "Risk level",
    actions: "Suggested actions",
    geoFocus: "Geo focus",
    keywords: "Suggested keywords",
    recommendedFormatLabel: "Recommended format",
    crisisMonitor: "Crisis monitor",
    crisisPriority: "Priority",
    noCrisisAlerts: "No strong crisis alerts right now.",
    mexicoHeatmap: "Mexico heatmap",
    regionalPulse: "Regional pulse",
    sourceFilter: "Source",
    categoryFilter: "Category",
    allSources: "All",
    allCategories: "All",
    stateDetail: "State detail",
    topTrendsInState: "Strong trends in this area",
    dominantSources: "Dominant sources",
    dominantCategories: "Dominant categories",
    heatLegend: "Map legend",
    lowIntensity: "Low",
    mediumIntensity: "Medium",
    highIntensity: "High",
    openTrendDetail: "Open detail",
    clickStateHint: "Click a state to view trends and context.",
    hoverStateHint: "Hover the map to preview regional pulse.",
    noStateSelected: "Select a state on the map to see details.",
    generalCategory: "General",
    highSeverity: "High",
    mediumSeverity: "Medium",
    lowSeverity: "Low",
    noGeoData: "No strong regional data.",
    positive: "Positive",
    negative: "Negative",
    mixed: "Mixed",
    emerging: "Emerging",
    peak: "Peak",
    fading: "Fading",
    temporalComparison: "Temporal comparison",
    historicalEvolution: "Historical evolution",
    realHistorySeries: "Series built from real snapshots stored in the database",
    vsPreviousCapture: "vs previous capture",
    risingNow: "Rising now",
    coolingDown: "Cooling down",
    newEntries: "New entries",
    viewDetail: "View detail",
    close: "Close",
    temporalDetail: "Temporal detail",
    dataOrigin: "Data provenance",
    methodologyNote: "Methodology",
    loadingData: "Loading data",
    loadingDataMessage: "Trend Flow is querying sources and preparing this view.",
    loadFailed: "We could not load this view",
    loadFailedMessage: "You can retry or check whether the backend is available.",
    retry: "Retry",
    methodologyTitle: "How to read this view",
    academicPositioning:
      "Trend Flow is a monitoring and decision-support platform. Some layers are real and others are estimated or heuristic.",
  },
};

export function useCopy() {
  const { preferences } = useAppPreferences();
  return copy[preferences.language];
}
